create table if not exists public.dealership_applications (
  id bigint generated by default as identity primary key,
  dealer_name text not null,
  firm_name text not null,
  mobile text not null,
  whatsapp text,
  email text not null,
  address text not null,
  district text not null,
  state text not null,
  pincode text not null,
  deposit_amount numeric(12, 2),
  experience text,
  message text,
  status text not null default 'New',
  created_at timestamptz not null default now()
);

-- Adds the field for projects where this table was created before deposit_amount existed.
alter table public.dealership_applications
  add column if not exists deposit_amount numeric(12, 2);

alter table public.dealership_applications enable row level security;

drop policy if exists "Anyone can submit dealership applications"
  on public.dealership_applications;

create policy "Anyone can submit dealership applications"
  on public.dealership_applications
  for insert
  to anon
  with check (true);

drop policy if exists "Authenticated users can manage dealership applications"
  on public.dealership_applications;

create policy "Authenticated users can manage dealership applications"
  on public.dealership_applications
  for all
  to authenticated
  using (true)
  with check (true);
