create table if not exists public.farmer_demos (
  id bigint generated by default as identity primary key,
  farmer_name text not null,
  mobile text not null,
  village text not null,
  taluka text,
  district text,
  crop_name text not null,
  demo_product text not null,
  demo_crop_name text,
  demo_area text,
  crop_stage_days text,
  application_method text not null,
  demo_date date not null,
  follow_up_date date,
  days_after_demo text,
  final_observation text,
  before_image_url text,
  after_image_url text,
  officer_name text,
  report_location text,
  status text not null default 'New',
  created_at timestamptz not null default now()
);
alter table public.farmer_demos enable row level security;
drop policy if exists "Anyone can submit farmer demos" on public.farmer_demos;
create policy "Anyone can submit farmer demos" on public.farmer_demos for insert to anon with check (true);
drop policy if exists "Authenticated users can manage farmer demos" on public.farmer_demos;
create policy "Authenticated users can manage farmer demos" on public.farmer_demos for all to authenticated using (true) with check (true);

alter table public.farmer_demos add column if not exists before_image_url text, add column if not exists after_image_url text;
insert into storage.buckets (id, name, public) values ('farmer-demo-images', 'farmer-demo-images', true) on conflict (id) do update set public = true;
drop policy if exists "Anyone can upload farmer demo images" on storage.objects;
create policy "Anyone can upload farmer demo images" on storage.objects for insert to anon with check (bucket_id = 'farmer-demo-images');
