create sequence if not exists public.lucky_draw_coupon_number_seq start with 1;

create table if not exists public.lucky_draw_coupons (
  id bigint generated by default as identity primary key,
  coupon_number text not null unique default ('RLF-LD-' || lpad(nextval('public.lucky_draw_coupon_number_seq')::text, 6, '0')),
  dealer_name text not null,
  shop_name text not null,
  address text not null,
  mobile text not null,
  coupon_amount numeric(12, 2) not null check (coupon_amount >= 0),
  status text not null default 'Active' check (status in ('Active', 'Used', 'Cancelled')),
  created_at timestamptz not null default now()
);

alter table public.lucky_draw_coupons add column if not exists shop_name text;

drop function if exists public.create_lucky_draw_coupon(text, text, text, numeric);

alter table public.lucky_draw_coupons enable row level security;

create or replace function public.create_lucky_draw_coupon(
  p_dealer_name text,
  p_shop_name text,
  p_address text,
  p_mobile text,
  p_coupon_amount numeric
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  new_coupon_number text;
  next_serial bigint;
begin
  if auth.uid() is null then
    raise exception 'Admin sign-in is required to create coupons';
  end if;

  -- Lock allocation so two admins cannot receive the same recycled number.
  perform pg_advisory_xact_lock(987654321);
  select candidate into next_serial
  from generate_series(
    1,
    coalesce((select max(substring(coupon_number from '[0-9]+$')::bigint) from public.lucky_draw_coupons), 0) + 1
  ) as candidate
  where not exists (
    select 1 from public.lucky_draw_coupons
    where coupon_number = 'RLF-LD-' || lpad(candidate::text, 6, '0')
  )
  order by candidate
  limit 1;

  new_coupon_number := 'RLF-LD-' || lpad(next_serial::text, 6, '0');
  insert into public.lucky_draw_coupons (coupon_number, dealer_name, shop_name, address, mobile, coupon_amount)
  values (new_coupon_number, p_dealer_name, p_shop_name, p_address, p_mobile, p_coupon_amount);
  return new_coupon_number;
end;
$$;

revoke execute on function public.create_lucky_draw_coupon(text, text, text, text, numeric) from public, anon;
grant execute on function public.create_lucky_draw_coupon(text, text, text, text, numeric) to authenticated;

drop policy if exists "Authenticated users can manage lucky draw coupons" on public.lucky_draw_coupons;
create policy "Authenticated users can manage lucky draw coupons"
  on public.lucky_draw_coupons for all to authenticated using (true) with check (true);
