import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiCamera, FiCheckCircle, FiLogOut, FiMapPin, FiPower, FiRefreshCw } from "react-icons/fi";
import { supabase } from "../supabase";

const initialVisit = { visit_type: "Dealer", customer_name: "", village: "", notes: "" };
const initialTransaction = { transaction_type: "Order", party_name: "", amount: "", details: "" };
const getLocation = () => new Promise((resolve, reject) => navigator.geolocation ? navigator.geolocation.getCurrentPosition((p) => resolve({ latitude: p.coords.latitude, longitude: p.coords.longitude }), reject, { enableHighAccuracy: true, timeout: 15000 }) : reject(new Error("GPS is not supported by this device.")));

export default function EmployeePortal() {
  const navigate = useNavigate(); const [profile, setProfile] = useState(null); const [attendance, setAttendance] = useState(null); const [visits, setVisits] = useState([]); const [tab, setTab] = useState("home"); const [visit, setVisit] = useState(initialVisit); const [transaction, setTransaction] = useState(initialTransaction); const [report, setReport] = useState({ summary: "", next_plan: "" }); const [photo, setPhoto] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const date = new Date().toISOString().slice(0, 10);
  const flash = (text) => { setMessage(text); setTimeout(() => setMessage(""), 3500); };
  const load = async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { navigate("/employee-tracking/login", { replace: true }); return; } const [{ data: p }, { data: a }, { data: v }, { data: r }] = await Promise.all([supabase.from("employee_profiles").select("*").eq("id", user.id).single(), supabase.from("employee_attendance").select("*").eq("employee_id", user.id).eq("work_date", date).maybeSingle(), supabase.from("employee_visits").select("*").eq("employee_id", user.id).gte("checked_in_at", `${date}T00:00:00`).order("checked_in_at", { ascending: false }), supabase.from("employee_daily_reports").select("*").eq("employee_id", user.id).eq("report_date", date).maybeSingle()]); if (!p || p.role !== "employee") { await supabase.auth.signOut(); navigate("/employee-tracking/login", { replace: true }); return; } setProfile(p); setAttendance(a); setVisits(v || []); if (r) setReport({ summary: r.summary || "", next_plan: r.next_plan || "" }); };
  useEffect(() => { load(); }, []);
  async function startDay() { setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); const { data, error } = await supabase.from("employee_attendance").insert({ employee_id: user.id, work_date: date, start_latitude: loc.latitude, start_longitude: loc.longitude }).select().single(); if (error) throw error; setAttendance(data); flash("Day started. Your attendance and GPS location were recorded."); } catch (e) { flash(e.message || "Unable to start day. Please allow location access."); } finally { setBusy(false); } }
  async function endDay() { setBusy(true); try { const loc = await getLocation(); const { error } = await supabase.from("employee_attendance").update({ end_time: new Date().toISOString(), end_latitude: loc.latitude, end_longitude: loc.longitude }).eq("id", attendance.id); if (error) throw error; setAttendance({ ...attendance, end_time: new Date().toISOString() }); flash("Day ended and final location recorded."); } catch (e) { flash(e.message || "Unable to end day."); } finally { setBusy(false); } }
  async function saveVisit(e) { e.preventDefault(); setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); let photo_url = null; if (photo) { const ext = photo.name.split(".").pop() || "jpg"; const path = `${user.id}/${crypto.randomUUID()}.${ext}`; const { error: uploadError } = await supabase.storage.from("employee-visit-photos").upload(path, photo, { contentType: photo.type }); if (uploadError) throw uploadError; photo_url = supabase.storage.from("employee-visit-photos").getPublicUrl(path).data.publicUrl; } const { error } = await supabase.from("employee_visits").insert({ ...visit, employee_id: user.id, photo_url, ...loc }); if (error) throw error; setVisit(initialVisit); setPhoto(null); await load(); setTab("home"); flash("Visit check-in saved with GPS location."); } catch (e) { flash(e.message || "Unable to save visit."); } finally { setBusy(false); } }
  async function saveReport(e) { e.preventDefault(); setBusy(true); try { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("employee_daily_reports").upsert({ employee_id: user.id, report_date: date, ...report }, { onConflict: "employee_id,report_date" }); if (error) throw error; flash("Daily report saved."); setTab("home"); } catch (e) { flash(e.message || "Unable to save report."); } finally { setBusy(false); } }
  async function saveTransaction(e) { e.preventDefault(); setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("employee_transactions").insert({ ...transaction, employee_id: user.id, amount: Number(transaction.amount), ...loc }); if (error) throw error; setTransaction(initialTransaction); flash(`${transaction.transaction_type} saved.`); setTab("home"); } catch (e) { flash(e.message || "Unable to save transaction."); } finally { setBusy(false); } }
  if (!profile) return <Loading />;
  const ended = Boolean(attendance?.end_time);
  return <main className="min-h-screen bg-slate-50 text-slate-800"><header className="border-b bg-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><img src="/logo.png" className="h-10 w-10 rounded-xl object-cover" alt="Reliaf" /><div><p className="font-black text-emerald-800">Reliaf Track</p><p className="text-xs text-slate-500">{profile.full_name} · {profile.territory || "Field employee"}</p></div></div><button onClick={async () => { await supabase.auth.signOut(); navigate("/employee-tracking/login"); }} className="rounded-lg p-2 text-slate-500" title="Logout"><FiLogOut /></button></div></header><section className="mx-auto max-w-3xl px-4 py-7"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Employee app</p><h1 className="mt-1 text-3xl font-black">{tab === "home" ? "My workday" : tab === "visit" ? "Visit check-in" : tab === "report" ? "Daily report" : "Order, collection or expense"}</h1></div>{tab !== "home" && <button onClick={() => setTab("home")} className="text-sm font-bold text-emerald-700">Back</button>}</div>{tab === "home" && <Home attendance={attendance} ended={ended} busy={busy} startDay={startDay} endDay={endDay} visits={visits} setTab={setTab} />} {tab === "visit" && <VisitForm value={visit} setValue={setVisit} photo={photo} setPhoto={setPhoto} submit={saveVisit} busy={busy} />} {tab === "report" && <ReportForm value={report} setValue={setReport} submit={saveReport} busy={busy} />} {tab === "transaction" && <TransactionForm value={transaction} setValue={setTransaction} submit={saveTransaction} busy={busy} />}</section>{message && <div className="fixed bottom-5 left-1/2 z-50 w-[calc(100%-2rem)] max-w-md -translate-x-1/2 rounded-xl bg-slate-900 px-4 py-3 text-center text-sm font-semibold text-white shadow-xl">{message}</div>}</main>;
}
function Home({ attendance, ended, busy, startDay, endDay, visits, setTab }) { const ready = attendance && !ended; return <><section className={`rounded-3xl p-6 text-white ${ready ? "bg-emerald-700" : "bg-slate-800"}`}><p className="text-sm text-white/70">Attendance status</p><h2 className="mt-2 text-2xl font-black">{ready ? "Day is active" : ended ? "Day completed" : "Ready to begin"}</h2><p className="mt-2 text-sm text-white/80">{ready ? `Started at ${new Date(attendance.start_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "Allow GPS access to record your attendance."}</p>{!attendance ? <button disabled={busy} onClick={startDay} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 font-bold text-emerald-800"><FiPower />{busy ? "Getting location…" : "Start day"}</button> : !ended && <button disabled={busy} onClick={endDay} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 font-bold text-slate-800"><FiPower />{busy ? "Getting location…" : "End day"}</button>}</section><div className="mt-6 grid gap-3 sm:grid-cols-3"><Action icon={<FiMapPin />} label="Visit check-in" onClick={() => setTab("visit")} disabled={!ready} /><Action icon={<FiCheckCircle />} label="Daily report" onClick={() => setTab("report")} disabled={!ready} /><Action icon={<FiRefreshCw />} label="Order / payment" onClick={() => setTab("transaction")} disabled={!ready} /></div><section className="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><h3 className="font-black">Today’s visits</h3><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">{visits.length} recorded</span></div>{visits.length ? <div className="mt-4 divide-y">{visits.map((v) => <div className="flex items-center gap-3 py-3" key={v.id}><span className="rounded-lg bg-emerald-100 p-2 text-emerald-700"><FiMapPin /></span><div className="flex-1"><p className="font-bold">{v.customer_name}</p><p className="text-xs text-slate-500">{v.visit_type} · {v.village || "No village added"}</p></div><span className="text-xs text-slate-400">{new Date(v.checked_in_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div> : <p className="mt-4 text-sm text-slate-500">No visits checked in yet.</p>}</section></>; }
function Action({ icon, label, onClick, disabled }) { return <button disabled={disabled} onClick={onClick} className="rounded-2xl bg-white p-4 text-left font-bold shadow-sm ring-1 ring-slate-200 transition hover:ring-emerald-400 disabled:cursor-not-allowed disabled:opacity-45"><span className="mb-3 inline-block rounded-lg bg-emerald-100 p-2 text-emerald-700">{icon}</span><span className="block">{label}</span></button>; }
function VisitForm({ value, setValue, photo, setPhoto, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><FiMapPin className="mr-2 inline" />Your GPS location will be saved when you check in.</p><Select label="Visit type" value={value.visit_type} onChange={(e) => setValue({ ...value, visit_type: e.target.value })} options={["Dealer", "Farmer"]} /><Field label="Dealer / farmer name" value={value.customer_name} onChange={(e) => setValue({ ...value, customer_name: e.target.value })} required /><Field label="Village / area" value={value.village} onChange={(e) => setValue({ ...value, village: e.target.value })} /><label className="block text-sm font-bold">Visit notes<textarea value={value.notes} onChange={(e) => setValue({ ...value, notes: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><label className="block text-sm font-bold">Visit photo (optional)<span className="mt-2 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed p-3 text-slate-500"><FiCamera />{photo ? photo.name : "Choose photo"}<input type="file" accept="image/*" capture="environment" className="hidden" onChange={(e) => setPhoto(e.target.files?.[0] || null)} /></span></label><Submit busy={busy} label="Save check-in" /></form>; }
function ReportForm({ value, setValue, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><label className="block text-sm font-bold">Today’s work summary<textarea required value={value.summary} onChange={(e) => setValue({ ...value, summary: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="5" placeholder="Visits completed, farmer feedback, work done..." /></label><label className="block text-sm font-bold">Tomorrow’s plan<textarea value={value.next_plan} onChange={(e) => setValue({ ...value, next_plan: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><Submit busy={busy} label="Save daily report" /></form>; }
function TransactionForm({ value, setValue, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><Select label="Entry type" value={value.transaction_type} onChange={(e) => setValue({ ...value, transaction_type: e.target.value })} options={["Order", "Collection", "Expense"]} /><Field label="Dealer / farmer / vendor" value={value.party_name} onChange={(e) => setValue({ ...value, party_name: e.target.value })} required /><Field label="Amount (₹)" type="number" min="0" value={value.amount} onChange={(e) => setValue({ ...value, amount: e.target.value })} required /><label className="block text-sm font-bold">Details<textarea value={value.details} onChange={(e) => setValue({ ...value, details: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><Submit busy={busy} label="Save entry" /></form>; }
function Field({ label, ...props }) { return <label className="block text-sm font-bold">{label}<input {...props} className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-emerald-500" /></label>; } function Select({ label, value, onChange, options }) { return <label className="block text-sm font-bold">{label}<select value={value} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 p-3">{options.map((o) => <option key={o}>{o}</option>)}</select></label>; } function Submit({ busy, label }) { return <button disabled={busy} className="w-full rounded-xl bg-emerald-700 py-3.5 font-bold text-white disabled:opacity-60">{busy ? "Saving…" : label}</button>; } function Loading() { return <div className="grid min-h-screen place-items-center font-bold text-emerald-700">Loading secure employee app…</div>; }
