import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiActivity, FiCalendar, FiCamera, FiCheckCircle, FiClock, FiCompass, FiFileText, FiHelpCircle, FiLogOut, FiMapPin, FiNavigation, FiPower, FiRefreshCw, FiTarget, FiTrendingUp, FiUsers, FiZap } from "react-icons/fi";
import { supabase } from "../supabase";

const initialVisit = { visit_type: "Dealer", customer_name: "", village: "", notes: "" };
const initialTransaction = { transaction_type: "Order", party_name: "", amount: "", details: "" };
const manager = { name: "Shriram Kulkarni", phone: "9075330820" };
const getLocation = () => new Promise((resolve, reject) => navigator.geolocation ? navigator.geolocation.getCurrentPosition((p) => resolve({ latitude: p.coords.latitude, longitude: p.coords.longitude }), reject, { enableHighAccuracy: true, timeout: 15000 }) : reject(new Error("GPS is not supported by this device.")));
const distanceBetween = (from, to) => { if (![from?.latitude, from?.longitude, to?.latitude, to?.longitude].every(Number.isFinite)) return 0; const radians = (value) => value * Math.PI / 180; const lat = radians(to.latitude - from.latitude); const lng = radians(to.longitude - from.longitude); const a = Math.sin(lat / 2) ** 2 + Math.cos(radians(from.latitude)) * Math.cos(radians(to.latitude)) * Math.sin(lng / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); };
const travelDistance = (attendance, visits, routePoints = []) => { if (!attendance) return 0; const savedPoints = routePoints.length ? routePoints.map((point) => ({ latitude: Number(point.latitude), longitude: Number(point.longitude) })) : [...visits].sort((a, b) => new Date(a.checked_in_at) - new Date(b.checked_in_at)).map((visit) => ({ latitude: Number(visit.latitude), longitude: Number(visit.longitude) })); const points = [{ latitude: Number(attendance.start_latitude), longitude: Number(attendance.start_longitude) }, ...savedPoints]; if (attendance.end_time) points.push({ latitude: Number(attendance.end_latitude), longitude: Number(attendance.end_longitude) }); return points.slice(1).reduce((total, point, index) => total + distanceBetween(points[index], point), 0); };

export default function EmployeePortal() {
  const navigate = useNavigate(); const [profile, setProfile] = useState(null); const [attendance, setAttendance] = useState(null); const [visits, setVisits] = useState([]); const [routePoints, setRoutePoints] = useState([]); const [tab, setTab] = useState("home"); const [visit, setVisit] = useState(initialVisit); const [transaction, setTransaction] = useState(initialTransaction); const [report, setReport] = useState({ summary: "", next_plan: "" }); const [photo, setPhoto] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const lastPoint = useRef(null);
  const date = new Date().toISOString().slice(0, 10);
  const flash = (text) => { setMessage(text); setTimeout(() => setMessage(""), 3500); };
  const load = async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { navigate("/employee-tracking/login", { replace: true }); return; } const [{ data: p }, { data: a }, { data: v }, { data: r }] = await Promise.all([supabase.from("employee_profiles").select("*").eq("id", user.id).single(), supabase.from("employee_attendance").select("*").eq("employee_id", user.id).eq("work_date", date).maybeSingle(), supabase.from("employee_visits").select("*").eq("employee_id", user.id).gte("checked_in_at", `${date}T00:00:00`).order("checked_in_at", { ascending: false }), supabase.from("employee_daily_reports").select("*").eq("employee_id", user.id).eq("report_date", date).maybeSingle()]); if (!p || p.role !== "employee") { await supabase.auth.signOut(); navigate("/employee-tracking/login", { replace: true }); return; } const { data: points } = a ? await supabase.from("employee_route_points").select("*").eq("attendance_id", a.id).order("recorded_at") : { data: [] }; setProfile(p); setAttendance(a); setVisits(v || []); setRoutePoints(points || []); if (r) setReport({ summary: r.summary || "", next_plan: r.next_plan || "" }); };
  useEffect(() => { load(); }, []);
  async function saveRoutePoint(attendanceRecord, point, source = "tracking") { const { data: { user } } = await supabase.auth.getUser(); if (!user || !attendanceRecord) return; const payload = { employee_id: user.id, attendance_id: attendanceRecord.id, latitude: point.latitude, longitude: point.longitude, accuracy_meters: point.accuracy || null, source }; const { data, error } = await supabase.from("employee_route_points").insert(payload).select().single(); if (error) throw error; lastPoint.current = { latitude: point.latitude, longitude: point.longitude, recordedAt: Date.now() }; setRoutePoints((current) => [...current, data]); }
  useEffect(() => { if (!attendance || attendance.end_time || !navigator.geolocation) return undefined; const latest = routePoints[routePoints.length - 1]; lastPoint.current = latest ? { latitude: Number(latest.latitude), longitude: Number(latest.longitude), recordedAt: new Date(latest.recorded_at).getTime() } : { latitude: Number(attendance.start_latitude), longitude: Number(attendance.start_longitude), recordedAt: new Date(attendance.start_time).getTime() }; const watchId = navigator.geolocation.watchPosition(async (position) => { const point = { latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy }; const previous = lastPoint.current; const movedMeters = distanceBetween(previous, point) * 1000; if (!previous || movedMeters >= 25 || Date.now() - previous.recordedAt >= 60000) { try { await saveRoutePoint(attendance, point); } catch { /* The workday remains usable if route tracking is temporarily unavailable. */ } } }, () => {}, { enableHighAccuracy: true, maximumAge: 15000, timeout: 30000 }); return () => navigator.geolocation.clearWatch(watchId); }, [attendance?.id, attendance?.end_time]);
  async function startDay() { setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); const { data, error } = await supabase.from("employee_attendance").insert({ employee_id: user.id, work_date: date, start_latitude: loc.latitude, start_longitude: loc.longitude }).select().single(); if (error) throw error; setAttendance(data); try { await saveRoutePoint(data, loc, "start"); } catch { /* Migration may not yet have been applied. */ } flash("Day started. GPS route tracking is active while this app is open."); } catch (e) { flash(e.message || "Unable to start day. Please allow location access."); } finally { setBusy(false); } }
  async function endDay() { setBusy(true); try { const loc = await getLocation(); const { error } = await supabase.from("employee_attendance").update({ end_time: new Date().toISOString(), end_latitude: loc.latitude, end_longitude: loc.longitude }).eq("id", attendance.id); if (error) throw error; try { await saveRoutePoint(attendance, loc, "end"); } catch { /* Migration may not yet have been applied. */ } setAttendance({ ...attendance, end_time: new Date().toISOString() }); flash("Day ended and final route location recorded."); } catch (e) { flash(e.message || "Unable to end day."); } finally { setBusy(false); } }
  async function saveVisit(e) { e.preventDefault(); setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); let photo_url = null; if (photo) { const ext = photo.name.split(".").pop() || "jpg"; const path = `${user.id}/${crypto.randomUUID()}.${ext}`; const { error: uploadError } = await supabase.storage.from("employee-visit-photos").upload(path, photo, { contentType: photo.type }); if (uploadError) throw uploadError; photo_url = supabase.storage.from("employee-visit-photos").getPublicUrl(path).data.publicUrl; } const { error } = await supabase.from("employee_visits").insert({ ...visit, employee_id: user.id, photo_url, ...loc }); if (error) throw error; setVisit(initialVisit); setPhoto(null); await load(); setTab("home"); flash("Visit check-in saved with GPS location."); } catch (e) { flash(e.message || "Unable to save visit."); } finally { setBusy(false); } }
  async function saveReport(e) { e.preventDefault(); setBusy(true); try { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("employee_daily_reports").upsert({ employee_id: user.id, report_date: date, ...report }, { onConflict: "employee_id,report_date" }); if (error) throw error; flash("Daily report saved."); setTab("home"); } catch (e) { flash(e.message || "Unable to save report."); } finally { setBusy(false); } }
  async function saveTransaction(e) { e.preventDefault(); setBusy(true); try { const loc = await getLocation(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("employee_transactions").insert({ ...transaction, employee_id: user.id, amount: Number(transaction.amount), ...loc }); if (error) throw error; setTransaction(initialTransaction); flash(`${transaction.transaction_type} saved.`); setTab("home"); } catch (e) { flash(e.message || "Unable to save transaction."); } finally { setBusy(false); } }
  if (!profile) return <Loading />;
  const ended = Boolean(attendance?.end_time);
  return <main className="min-h-screen bg-[#f6f8f7] text-slate-800"><header className="border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><img src="/logo.webp" className="h-10 w-10 rounded-xl object-cover" alt="Reliaf" /><div><p className="font-black text-emerald-800">Reliaf Track</p><p className="text-xs text-slate-500">{profile.full_name} · {profile.territory || "Field employee"}</p></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700 sm:block"><FiActivity className="mr-1 inline" /> GPS ready</span><button onClick={async () => { await supabase.auth.signOut(); navigate("/employee-tracking/login"); }} className="rounded-xl p-2.5 text-slate-500 transition hover:bg-slate-100 hover:text-rose-600" title="Logout"><FiLogOut /></button></div></div></header><section className="mx-auto max-w-5xl px-4 py-7 sm:px-6 sm:py-9"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Employee workspace</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{tab === "home" ? "My workday" : tab === "visit" ? "Visit check-in" : tab === "report" ? "Daily report" : "Order, collection or expense"}</h1></div>{tab !== "home" && <button onClick={() => setTab("home")} className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-emerald-700 shadow-sm ring-1 ring-slate-200">Back to dashboard</button>}</div>{tab === "home" && <Home attendance={attendance} ended={ended} busy={busy} startDay={startDay} endDay={endDay} visits={visits} routePoints={routePoints} setTab={setTab} onNotice={flash} />} {tab === "visit" && <VisitForm value={visit} setValue={setVisit} photo={photo} setPhoto={setPhoto} submit={saveVisit} busy={busy} />} {tab === "report" && <ReportForm value={report} setValue={setReport} submit={saveReport} busy={busy} />} {tab === "transaction" && <TransactionForm value={transaction} setValue={setTransaction} submit={saveTransaction} busy={busy} />}</section>{message && <div className="fixed bottom-5 left-1/2 z-50 w-[calc(100%-2rem)] max-w-md -translate-x-1/2 rounded-xl bg-slate-900 px-4 py-3 text-center text-sm font-semibold text-white shadow-xl">{message}</div>}</main>;
}
function Home({ attendance, ended, busy, startDay, endDay, visits, routePoints, setTab, onNotice }) {
  const ready = attendance && !ended;
  const dateLabel = new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "short" }).format(new Date());
  const progress = Math.min(100, visits.length * 20);
  const distance = travelDistance(attendance, visits, routePoints);
  const actions = [
    { icon: <FiMapPin />, label: "Visit check-in", hint: "Add customer visit", tone: "bg-emerald-50 text-emerald-700", onClick: () => setTab("visit") },
    { icon: <FiRefreshCw />, label: "Order & payment", hint: "Order, collection, expense", tone: "bg-violet-50 text-violet-700", onClick: () => setTab("transaction") },
    { icon: <FiFileText />, label: "Daily report", hint: "Share today’s update", tone: "bg-sky-50 text-sky-700", onClick: () => setTab("report") },
    { icon: <FiNavigation />, label: "Open my route", hint: "View your current place", tone: "bg-amber-50 text-amber-700", onClick: () => getLocation().then((location) => window.open(`https://www.google.com/maps?q=${location.latitude},${location.longitude}`, "_blank", "noopener,noreferrer")).catch(() => onNotice("Allow GPS access to open your location in Maps.")) },
    { icon: <FiUsers />, label: "Today’s visits", hint: "See checked-in customers", tone: "bg-rose-50 text-rose-700", onClick: () => document.getElementById("today-visits")?.scrollIntoView({ behavior: "smooth", block: "start" }) },
    { icon: <FiHelpCircle />, label: "Call manager", hint: `${manager.name} · ${manager.phone}`, tone: "bg-slate-100 text-slate-700", onClick: () => { onNotice(`Calling ${manager.name}…`); window.location.href = `tel:+91${manager.phone}`; } },
  ];
  return <>
    <section className={`relative overflow-hidden rounded-[28px] p-6 text-white shadow-xl shadow-slate-900/10 sm:p-8 ${ready ? "bg-gradient-to-br from-emerald-800 via-emerald-700 to-teal-700" : ended ? "bg-gradient-to-br from-slate-800 to-slate-700" : "bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-950"}`}>
      <div className="absolute -right-14 -top-16 h-48 w-48 rounded-full bg-lime-300/15 blur-2xl" /><div className="absolute bottom-0 right-20 h-28 w-28 rounded-full border-[18px] border-white/10" />
      <div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold"><FiCalendar /> {dateLabel}</div><p className="text-sm text-white/70">Attendance status</p><h2 className="mt-1 text-3xl font-black">{ready ? "You’re in the field" : ended ? "Workday completed" : "Ready to begin"}</h2><p className="mt-2 max-w-md text-sm leading-6 text-white/75">{ready ? `Started at ${new Date(attendance.start_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}. Your GPS location is being recorded securely.` : ended ? "Great work today. Your day-end location has been recorded." : "Start your day to unlock visits, orders and reporting."}</p></div><div>{!attendance ? <button disabled={busy} onClick={startDay} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 font-bold text-emerald-800 shadow-lg transition hover:-translate-y-0.5 disabled:opacity-60"><FiPower />{busy ? "Getting location…" : "Start my day"}</button> : !ended && <button disabled={busy} onClick={endDay} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 font-bold text-slate-800 shadow-lg transition hover:-translate-y-0.5 disabled:opacity-60"><FiPower />{busy ? "Getting location…" : "End my day"}</button>}</div></div>
    </section>
    <div className="-mt-1 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<FiClock />} value={ready ? "Active" : ended ? "Done" : "Not started"} label="Work status" /><Stat icon={<FiMapPin />} value={visits.length} label="Visits today" /><Stat icon={<FiNavigation />} value={`${distance.toFixed(1)} km`} label={routePoints.length ? "Tracked GPS distance" : "GPS distance"} /><Stat icon={<FiTrendingUp />} value={`${progress}%`} label="Daily target" /></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_.85fr]">
      <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Quick actions</p><h3 className="mt-1 text-xl font-black">What would you like to do?</h3></div><FiZap className="text-2xl text-amber-400" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{actions.map((action) => <Action key={action.label} {...action} disabled={!ready && action.label !== "Need support?"} />)}</div></section>
      <aside className="rounded-3xl bg-slate-900 p-6 text-white shadow-lg"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Today’s goal</p><h3 className="mt-1 text-xl font-black">8 quality visits</h3></div><FiTarget className="text-3xl text-lime-300" /></div><div className="mt-6 flex items-center gap-5"><div className="relative grid h-24 w-24 place-items-center rounded-full" style={{ background: `conic-gradient(#a3e635 ${progress * 3.6}deg, rgba(255,255,255,.14) 0deg)` }}><div className="grid h-[76px] w-[76px] place-items-center rounded-full bg-slate-900"><span className="text-lg font-black">{visits.length}<small className="text-xs text-white/60">/8</small></span></div></div><p className="text-sm leading-6 text-slate-300">{visits.length ? `${Math.max(0, 8 - visits.length)} more visits to reach today’s target.` : "Start with your first visit and build momentum."}</p></div><div className="mt-6 rounded-2xl bg-white/10 p-4"><p className="text-sm font-bold">Field tip</p><p className="mt-1 text-xs leading-5 text-slate-300">Add a photo and a useful note after each visit so your follow-up is always clear.</p></div></aside>
    </div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section id="today-visits" className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black">Today’s visits</h3><p className="mt-1 text-xs text-slate-500">Your latest field check-ins</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">{visits.length} recorded</span></div>{visits.length ? <div className="mt-4 divide-y divide-slate-100">{visits.map((v) => <div className="flex items-center gap-3 py-3" key={v.id}><span className="rounded-xl bg-emerald-100 p-2.5 text-emerald-700"><FiMapPin /></span><div className="flex-1"><p className="font-bold">{v.customer_name}</p><p className="text-xs text-slate-500">{v.visit_type} · {v.village || "No village added"}</p></div><span className="text-xs font-medium text-slate-400">{new Date(v.checked_in_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center"><FiCompass className="mx-auto text-2xl text-emerald-600" /><p className="mt-2 text-sm font-bold">Your field journey starts here</p><p className="mt-1 text-xs text-slate-500">Check in at a dealer or farmer visit to see it here.</p></div>}</section><section className="rounded-3xl border border-emerald-100 bg-emerald-50 p-6"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Next step</p><h3 className="mt-2 text-xl font-black text-emerald-950">Keep the office updated</h3><p className="mt-2 text-sm leading-6 text-emerald-800/75">Submit a concise report before ending your workday.</p><button disabled={!ready} onClick={() => setTab("report")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><FiCheckCircle /> Open daily report</button><a href={`tel:+91${manager.phone}`} className="mt-3 flex items-center gap-2 text-sm font-bold text-emerald-800 hover:underline"><FiHelpCircle /> Manager: {manager.name}</a></section></div>
  </>;
}
function Stat({ icon, value, label }) { return <div className="rounded-2xl bg-white px-4 py-3.5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700">{icon}</span><div><p className="font-black text-slate-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div></div>; }
function Action({ icon, label, hint, tone, onClick, disabled }) { return <button disabled={disabled} onClick={onClick} className="group flex items-center gap-3 rounded-2xl border border-slate-100 p-3.5 text-left transition hover:border-emerald-300 hover:shadow-md disabled:cursor-not-allowed disabled:opacity-45"><span className={`rounded-xl p-2.5 ${tone}`}>{icon}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{label}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{hint}</span></span><span className="text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-emerald-600">›</span></button>; }
function VisitForm({ value, setValue, photo, setPhoto, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><FiMapPin className="mr-2 inline" />Your GPS location will be saved when you check in.</p><Select label="Visit type" value={value.visit_type} onChange={(e) => setValue({ ...value, visit_type: e.target.value })} options={["Dealer", "Farmer"]} /><Field label="Dealer / farmer name" value={value.customer_name} onChange={(e) => setValue({ ...value, customer_name: e.target.value })} required /><Field label="Village / area" value={value.village} onChange={(e) => setValue({ ...value, village: e.target.value })} /><label className="block text-sm font-bold">Visit notes<textarea value={value.notes} onChange={(e) => setValue({ ...value, notes: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><label className="block text-sm font-bold">Visit photo (optional)<span className="mt-2 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed p-3 text-slate-500"><FiCamera />{photo ? photo.name : "Choose photo"}<input type="file" accept="image/*" capture="environment" className="hidden" onChange={(e) => setPhoto(e.target.files?.[0] || null)} /></span></label><Submit busy={busy} label="Save check-in" /></form>; }
function ReportForm({ value, setValue, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><label className="block text-sm font-bold">Today’s work summary<textarea required value={value.summary} onChange={(e) => setValue({ ...value, summary: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="5" placeholder="Visits completed, farmer feedback, work done..." /></label><label className="block text-sm font-bold">Tomorrow’s plan<textarea value={value.next_plan} onChange={(e) => setValue({ ...value, next_plan: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><Submit busy={busy} label="Save daily report" /></form>; }
function TransactionForm({ value, setValue, submit, busy }) { return <form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><Select label="Entry type" value={value.transaction_type} onChange={(e) => setValue({ ...value, transaction_type: e.target.value })} options={["Order", "Collection", "Expense"]} /><Field label="Dealer / farmer / vendor" value={value.party_name} onChange={(e) => setValue({ ...value, party_name: e.target.value })} required /><Field label="Amount (₹)" type="number" min="0" value={value.amount} onChange={(e) => setValue({ ...value, amount: e.target.value })} required /><label className="block text-sm font-bold">Details<textarea value={value.details} onChange={(e) => setValue({ ...value, details: e.target.value })} className="mt-2 w-full rounded-xl border p-3" rows="3" /></label><Submit busy={busy} label="Save entry" /></form>; }
function Field({ label, ...props }) { return <label className="block text-sm font-bold">{label}<input {...props} className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-emerald-500" /></label>; } function Select({ label, value, onChange, options }) { return <label className="block text-sm font-bold">{label}<select value={value} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 p-3">{options.map((o) => <option key={o}>{o}</option>)}</select></label>; } function Submit({ busy, label }) { return <button disabled={busy} className="w-full rounded-xl bg-emerald-700 py-3.5 font-bold text-white disabled:opacity-60">{busy ? "Saving…" : label}</button>; } function Loading() { return <div className="grid min-h-screen place-items-center font-bold text-emerald-700">Loading secure employee app…</div>; }
