import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiArrowRight, FiBarChart2, FiCheckCircle, FiLock, FiMapPin, FiUsers } from "react-icons/fi";
import { supabase } from "../supabase";

export default function EmployeeLogin({ admin = false }) {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function submit(event) {
    event.preventDefault(); setLoading(true); setError("");
    const { data, error: loginError } = await supabase.auth.signInWithPassword({ email, password });
    if (loginError) { setError(loginError.message); setLoading(false); return; }
    const { data: profile, error: profileError } = await supabase.from("employee_profiles").select("role").eq("id", data.user.id).single();
    if (profileError || !profile || (admin ? profile.role !== "admin" : profile.role !== "employee")) {
      await supabase.auth.signOut(); setError(admin ? "This account does not have administrator access." : "Please use an employee account to sign in."); setLoading(false); return;
    }
    navigate(admin ? "/employee-tracking/admin" : "/employee-tracking/employee", { replace: true });
  }
  const portal = admin ? "Command center" : "Field force portal";
  return <main className="relative grid min-h-screen overflow-hidden bg-[#082c24] lg:grid-cols-[1.1fr_.9fr]"><div className="absolute -left-20 top-20 h-72 w-72 rounded-full bg-lime-300/10 blur-3xl" /><div className="absolute -bottom-24 right-1/3 h-80 w-80 rounded-full bg-emerald-400/10 blur-3xl" />
    <section className="relative hidden min-h-screen flex-col justify-between overflow-hidden p-10 text-white lg:flex"><div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.055)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.055)_1px,transparent_1px)] bg-[size:46px_46px] [mask-image:linear-gradient(to_bottom,black,transparent)]" /><a href="/" className="relative flex items-center gap-3"><img src="/logo.webp" alt="Reliaf" className="h-12 w-12 rounded-2xl object-cover" /><div><p className="text-xl font-black">Reliaf Track</p><p className="text-xs text-emerald-100/70">Field force management</p></div></a><div className="relative max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold text-emerald-100"><FiBarChart2 /> {portal}</span><h1 className="mt-6 text-5xl font-black leading-[1.06]">See the field.<br /><span className="text-lime-300">Lead with clarity.</span></h1><p className="mt-6 max-w-md text-lg leading-8 text-emerald-50/75">Track attendance, customer visits, orders and collections from one secure place.</p><div className="mt-10 grid grid-cols-3 gap-3">{[[FiUsers, "Team activity"], [FiMapPin, "GPS visits"], [FiCheckCircle, "Daily reports"]].map(([Icon, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><Icon className="text-xl text-lime-300" /><p className="mt-3 text-xs font-bold text-emerald-50">{label}</p></div>)}</div></div><p className="relative text-xs font-medium text-emerald-100/50">Secure access for authorized Reliaf team members</p></section>
    <section className="relative flex items-center justify-center bg-[#f7faf8] px-4 py-10 sm:px-8"><div className="w-full max-w-md"><a href="/" className="flex items-center gap-3 lg:hidden"><img src="/logo.webp" alt="Reliaf" className="h-11 w-11 rounded-xl object-cover" /><span className="text-xl font-black text-emerald-900">Reliaf Track</span></a><div className="mt-10 rounded-[28px] bg-white p-7 shadow-2xl shadow-emerald-950/10 ring-1 ring-slate-200/70 sm:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-xl text-emerald-700"><FiLock /></div><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">{portal}</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-900">{admin ? "Welcome back" : "Start your workday"}</h2><p className="mt-3 text-sm leading-6 text-slate-500">Sign in to securely access your {admin ? "live team dashboard and performance overview" : "daily field activities and visit tools"}.</p></div><form className="mt-7 space-y-4" onSubmit={submit}><label className="block text-sm font-bold text-slate-700">Work email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 outline-none transition focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100" placeholder="name@company.com" /></label><label className="block text-sm font-bold text-slate-700">Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 outline-none transition focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100" placeholder="Your password" /></label>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}<button disabled={loading} className="group flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 py-3.5 font-bold text-white shadow-lg shadow-emerald-700/20 transition hover:bg-emerald-800 disabled:opacity-60">{loading ? "Signing in…" : "Sign in securely"}<FiArrowRight className="transition group-hover:translate-x-1" /></button></form><div className="mt-6 flex items-center gap-2 text-xs text-slate-400"><FiLock /> Your login is protected and role-based.</div><p className="mt-6 border-t border-slate-100 pt-6 text-center text-sm text-slate-500">{admin ? "Field employee?" : "Administrator?"} <a className="font-bold text-emerald-700 hover:underline" href={admin ? "/employee-tracking/login" : "/employee-tracking/admin-login"}>{admin ? "Employee login" : "Admin login"}</a></p></div></div></section></main>;
}
