import { useState } from "react";
import { Helmet } from "react-helmet-async";
import { supabase } from "../supabase";

const copy = {
  en: { title: "Farmer Demonstration Report", intro: "Record a crop demonstration and follow-up observation.", farmer: "Farmer name", mobile: "Mobile number", village: "Village", taluka: "Taluka", district: "District", crop: "Crop name", product: "Demo product", demoCrop: "Crop used for demo", area: "Demo area", stage: "Crop stage / days", method: "Application method", demoDate: "Demo date", followDate: "Follow-up inspection date", days: "Days after demo", observation: "Final observation after demo", officer: "Officer name and designation", location: "Report submission location", before: "Before demonstration photo", after: "After demonstration photo", submit: "Submit demonstration report", success: "Thank you. The farmer demonstration report has been submitted." },
  mr: { title: "शेतकरी पीक प्रात्यक्षिक अहवाल", intro: "पीक प्रात्यक्षिक आणि पाहणीची माहिती नोंदवा.", farmer: "शेतकऱ्याचे नाव", mobile: "मोबाईल क्रमांक", village: "गाव", taluka: "तालुका", district: "जिल्हा", crop: "पिकाचे नाव", product: "डेमो प्रोडक्ट", demoCrop: "डेमो दिलेल्या पिकाचे नाव", area: "डेमो क्षेत्र", stage: "पिकाची अवस्था / दिवस", method: "डेमो देण्याची पद्धत", demoDate: "डेमो दिनांक", followDate: "पाहणी दिनांक", days: "डेमो नंतरचे दिवस", observation: "डेमो नंतरचे अंतिम निरीक्षण", officer: "अधिकाऱ्याचे नाव व पद", location: "अहवाल सादर केलेले ठिकाण", before: "प्रात्यक्षिकापूर्वीचा फोटो", after: "प्रात्यक्षिकानंतरचा फोटो", submit: "अहवाल सादर करा", success: "धन्यवाद. पीक प्रात्यक्षिक अहवाल सादर झाला आहे." },
  hi: { title: "किसान फसल प्रदर्शन रिपोर्ट", intro: "फसल प्रदर्शन और निरीक्षण की जानकारी दर्ज करें।", farmer: "किसान का नाम", mobile: "मोबाइल नंबर", village: "गाँव", taluka: "तहसील", district: "जिला", crop: "फसल का नाम", product: "डेमो प्रोडक्ट", demoCrop: "डेमो वाली फसल का नाम", area: "डेमो क्षेत्र", stage: "फसल की अवस्था / दिन", method: "प्रयोग विधि", demoDate: "डेमो की तारीख", followDate: "फॉलो-अप निरीक्षण तारीख", days: "डेमो के बाद दिन", observation: "डेमो के बाद अंतिम निरीक्षण", officer: "अधिकारी का नाम व पद", location: "रिपोर्ट जमा करने का स्थान", before: "प्रदर्शन से पहले की फोटो", after: "प्रदर्शन के बाद की फोटो", submit: "रिपोर्ट जमा करें", success: "धन्यवाद। किसान प्रदर्शन रिपोर्ट जमा हो गई है।" },
};
const initial = { farmer_name:"", mobile:"", village:"", taluka:"", district:"", crop_name:"", demo_product:"", demo_crop_name:"", demo_area:"", crop_stage_days:"", application_method:"Spray", demo_date:"", follow_up_date:"", days_after_demo:"", final_observation:"", officer_name:"", report_location:"" };
const fileError = (file) => !file || file.type.startsWith("image/") && file.size <= 5 * 1024 * 1024 ? "" : "Please upload an image smaller than 5 MB.";

export default function FarmerDemo() {
  const [lang,setLang]=useState("en"), [form,setForm]=useState(initial), [beforeFile,setBeforeFile]=useState(null), [afterFile,setAfterFile]=useState(null), [saving,setSaving]=useState(false), [success,setSuccess]=useState(false); const t=copy[lang];
  const change=(e)=>setForm({...form,[e.target.name]:e.target.value});
  const uploadImage = async (file, type) => { if (!file) return null; const extension=file.name.split(".").pop() || "jpg"; const path=`${type}/${crypto.randomUUID()}.${extension}`; const { error }=await supabase.storage.from("farmer-demo-images").upload(path,file,{contentType:file.type,upsert:false}); if(error) throw error; return supabase.storage.from("farmer-demo-images").getPublicUrl(path).data.publicUrl; };
  const submit=async(e)=>{e.preventDefault(); const beforeError=fileError(beforeFile), afterError=fileError(afterFile); if(beforeError||afterError)return alert(beforeError||afterError); setSaving(true); try { const [before_image_url,after_image_url]=await Promise.all([uploadImage(beforeFile,"before"),uploadImage(afterFile,"after")]); const {error}=await supabase.from("farmer_demos").insert({...form,before_image_url,after_image_url}); if(error)throw error; setSuccess(true);setForm(initial);setBeforeFile(null);setAfterFile(null);e.target.reset(); } catch(error) { alert(error.message || "Unable to submit the report."); } finally { setSaving(false); } };
  const field=(name,label,type="text",required=false)=><label className="grid gap-2 font-semibold text-slate-700">{label}{required&&" *"}<input required={required} type={type} name={name} value={form[name]} onChange={change} className="min-h-12 rounded-xl border border-slate-200 px-4 outline-none focus:border-green-700 focus:ring-4 focus:ring-green-100" /></label>;
  const imageField=(label,setter)=><label className="grid gap-2 font-semibold text-slate-700">{label}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(e)=>setter(e.target.files?.[0] || null)} className="min-h-12 rounded-xl border border-dashed border-green-300 bg-green-50 p-3 text-sm" /><span className="text-xs font-normal text-slate-500">Optional: JPG, PNG, or WebP up to 5 MB.</span></label>;
  return <main className="min-h-screen bg-green-50 px-4 py-10 sm:px-6"><Helmet><title>Farmer Demo Report | Reliaf Agrotech</title></Helmet><div className="mx-auto max-w-4xl rounded-3xl bg-white p-5 shadow-xl sm:p-10"><div className="flex flex-wrap justify-between gap-4"><a href="/" className="font-bold text-green-700">← Back to Home</a><select value={lang} onChange={(e)=>setLang(e.target.value)} className="rounded-lg border px-3 py-2"><option value="en">English</option><option value="mr">मराठी</option><option value="hi">हिंदी</option></select></div><h1 className="mt-8 text-3xl font-black text-green-800">{t.title}</h1><p className="mt-2 text-slate-600">{t.intro}</p>{success&&<p className="mt-6 rounded-xl bg-green-50 p-4 font-semibold text-green-800">{t.success}</p>}<form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2">{field("farmer_name",t.farmer,"text",true)}{field("mobile",t.mobile,"tel",true)}{field("village",t.village,"text",true)}{field("taluka",t.taluka)}{field("district",t.district)}{field("crop_name",t.crop,"text",true)}{field("demo_product",t.product,"text",true)}{field("demo_crop_name",t.demoCrop)}{field("demo_area",t.area)}{field("crop_stage_days",t.stage)}<label className="grid gap-2 font-semibold text-slate-700">{t.method}<select name="application_method" value={form.application_method} onChange={change} className="min-h-12 rounded-xl border border-slate-200 px-4"><option>Spray</option><option>Drip irrigation</option><option>Soil application</option><option>Top dressing</option><option>Other</option></select></label>{field("demo_date",t.demoDate,"date",true)}{field("follow_up_date",t.followDate,"date")}{field("days_after_demo",t.days)}{imageField(t.before,setBeforeFile)}{imageField(t.after,setAfterFile)}<label className="grid gap-2 font-semibold text-slate-700 sm:col-span-2">{t.observation}<textarea name="final_observation" value={form.final_observation} onChange={change} rows="4" className="rounded-xl border border-slate-200 p-4" /></label>{field("officer_name",t.officer)}{field("report_location",t.location)}<button disabled={saving} className="min-h-12 rounded-xl bg-green-700 px-6 font-bold text-white sm:col-span-2">{saving?"Submitting...":t.submit}</button></form></div></main>;
}
