import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiActivity, FiChevronRight, FiClock, FiDollarSign, FiLogOut, FiMapPin, FiNavigation, FiRefreshCw, FiTrendingUp, FiUsers } from "react-icons/fi";
import { supabase } from "../supabase";

const today = () => new Date().toISOString().slice(0, 10);
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;
const initials = (name = "?") => name.split(" ").map((part) => part[0]).slice(0, 2).join("");
const distanceBetween = (from, to) => { if (![from?.latitude, from?.longitude, to?.latitude, to?.longitude].every(Number.isFinite)) return 0; const radians = (value) => value * Math.PI / 180; const lat = radians(to.latitude - from.latitude); const lng = radians(to.longitude - from.longitude); const a = Math.sin(lat / 2) ** 2 + Math.cos(radians(from.latitude)) * Math.cos(radians(to.latitude)) * Math.sin(lng / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); };
const employeeDistance = (attendance, visits, routePoints = []) => { if (!attendance) return 0; const tracked = routePoints.filter((point) => point.attendance_id === attendance.id).sort((a, b) => new Date(a.recorded_at) - new Date(b.recorded_at)); const savedPoints = tracked.length ? tracked : visits.filter((visit) => visit.employee_id === attendance.employee_id).sort((a, b) => new Date(a.checked_in_at) - new Date(b.checked_in_at)); const points = [{ latitude: Number(attendance.start_latitude), longitude: Number(attendance.start_longitude) }, ...savedPoints.map((point) => ({ latitude: Number(point.latitude), longitude: Number(point.longitude) }))]; if (attendance.end_time) points.push({ latitude: Number(attendance.end_latitude), longitude: Number(attendance.end_longitude) }); return points.slice(1).reduce((total, point, index) => total + distanceBetween(points[index], point), 0); };

export default function TrackingAdmin({ embedded = false }) {
  const navigate = useNavigate();
  const [data, setData] = useState({ profiles: [], attendance: [], visits: [], transactions: [], routePoints: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() {
    setLoading(true); setError("");
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { navigate("/employee-tracking/admin-login", { replace: true }); return; }
    const { data: me } = await supabase.from("employee_profiles").select("role").eq("id", user.id).single();
    if (me?.role !== "admin") { await supabase.auth.signOut(); navigate("/employee-tracking/admin-login", { replace: true }); return; }
    const start = `${today()}T00:00:00`;
    const results = await Promise.all([
      supabase.from("employee_profiles").select("*").eq("role", "employee").order("full_name"),
      supabase.from("employee_attendance").select("*, employee_profiles(full_name, territory)").eq("work_date", today()),
      supabase.from("employee_visits").select("*, employee_profiles(full_name, territory)").gte("checked_in_at", start).order("checked_in_at", { ascending: false }),
      supabase.from("employee_transactions").select("*, employee_profiles(full_name)").gte("created_at", start).order("created_at", { ascending: false }),
      supabase.from("employee_route_points").select("*").gte("recorded_at", start).order("recorded_at"),
    ]);
    const firstError = results.find((result) => result.error)?.error;
    if (firstError) setError(firstError.message);
    setData({ profiles: results[0].data || [], attendance: results[1].data || [], visits: results[2].data || [], transactions: results[3].data || [], routePoints: results[4].data || [] }); setLoading(false);
  }
  useEffect(() => { load(); }, []);
  const stats = useMemo(() => {
    const active = data.attendance.filter((item) => !item.end_time);
    const orders = data.transactions.filter((item) => item.transaction_type === "Order").reduce((sum, item) => sum + Number(item.amount || 0), 0);
    const collections = data.transactions.filter((item) => item.transaction_type === "Collection").reduce((sum, item) => sum + Number(item.amount || 0), 0);
    return { active, orders, collections, attendanceRate: data.profiles.length ? Math.round((data.attendance.length / data.profiles.length) * 100) : 0 };
  }, [data]);
  const content = <section className={embedded ? "" : "mx-auto max-w-7xl px-4 py-7 sm:px-6 sm:py-9"}>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Live operations</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Today’s field activity</h1><p className="mt-2 text-sm text-slate-500">{new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-emerald-700/20 transition hover:bg-emerald-800"><FiRefreshCw className={loading ? "animate-spin" : ""} /> Refresh data</button></div>
    {error && <p className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}. Make sure the employee tracking SQL migration has been run.</p>}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<FiUsers />} label="Field employees" value={data.profiles.length} note={`${data.profiles.length - data.attendance.length} not started`} tone="emerald" /><Metric icon={<FiActivity />} label="Active now" value={stats.active.length} note="Sharing field activity" tone="lime" /><Metric icon={<FiMapPin />} label="Visits today" value={data.visits.length} note="Customer check-ins" tone="sky" /><Metric icon={<FiDollarSign />} label="Order value" value={money(stats.orders)} note="Today’s orders" tone="violet" /><Metric icon={<FiTrendingUp />} label="Collections" value={money(stats.collections)} note="Received today" tone="amber" /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-5 sm:px-6"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Team pulse</p><h2 className="mt-1 text-xl font-black">Attendance & visit progress</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">{stats.attendanceRate}% attendance</span></div><div className="grid gap-7 p-5 sm:grid-cols-[.85fr_1.15fr] sm:p-6"><div className="flex flex-col items-center justify-center"><ProgressRing value={stats.attendanceRate} /><p className="mt-4 text-sm font-bold text-slate-800">{data.attendance.length} of {data.profiles.length} checked in</p><p className="mt-1 text-center text-xs text-slate-500">Current field-team attendance</p></div><div><div className="flex items-center justify-between"><p className="font-bold">Visit activity</p><p className="text-xs font-semibold text-emerald-700">{data.visits.length} check-ins</p></div><div className="mt-5 flex h-32 items-end justify-between gap-2 border-b border-slate-100 pb-1">{[28, 45, 34, 68, 55, 82, Math.max(16, Math.min(100, data.visits.length * 12))].map((height, index) => <div className="flex flex-1 items-end" key={index}><div className={`w-full rounded-t-md ${index === 6 ? "bg-emerald-600" : "bg-emerald-100"}`} style={{ height: `${height}%` }} /></div>)}</div><div className="mt-2 flex justify-between text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>9 AM</span><span>12 PM</span><span>3 PM</span><span>Now</span></div><div className="mt-5 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><FiClock className="mr-1 inline text-emerald-700" /> Data refreshes when you select <b>Refresh data</b>.</div></div></div></section>
      <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-800 to-teal-800 p-6 text-white shadow-xl shadow-emerald-900/15"><div className="absolute -right-12 -top-14 h-44 w-44 rounded-full border-[22px] border-white/10" /><div className="relative"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-100">Live field coverage</p><h2 className="mt-1 text-xl font-black">{stats.active.length} team members active</h2></div><FiNavigation className="text-3xl text-lime-300" /></div><div className="mt-6 space-y-3">{stats.active.slice(0, 3).map((item) => <a key={item.id} target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${item.start_latitude},${item.start_longitude}`} className="flex items-center gap-3 rounded-2xl bg-white/10 p-3 transition hover:bg-white/15"><span className="grid h-9 w-9 place-items-center rounded-full bg-lime-300 text-xs font-black text-emerald-950">{initials(item.employee_profiles?.full_name)}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{item.employee_profiles?.full_name}</span><span className="text-xs text-emerald-100/70">{item.employee_profiles?.territory || "Field route"} · {employeeDistance(item, data.visits, data.routePoints).toFixed(1)} km</span></span><FiChevronRight /></a>)}{!stats.active.length && <p className="rounded-2xl bg-white/10 p-4 text-sm leading-6 text-emerald-50/80">Employees who start their day will appear here with their GPS start location.</p>}</div></div></section></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel eyebrow="Team directory" title="Employees & attendance"><div className="divide-y divide-slate-100">{data.profiles.length ? data.profiles.map((profile) => { const attendance = data.attendance.find((item) => item.employee_id === profile.id); const state = attendance && !attendance.end_time ? ["In field", "bg-emerald-100 text-emerald-700"] : attendance ? ["Completed", "bg-slate-100 text-slate-600"] : ["Not started", "bg-amber-100 text-amber-700"]; return <div className="flex items-center gap-3 py-3.5" key={profile.id}><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 text-sm font-black text-emerald-700">{initials(profile.full_name)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{profile.full_name}</p><p className="text-xs text-slate-500">{profile.territory || "No territory assigned"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state[1]}`}>{state[0]}</span></div>; }) : <Empty text="No employee profiles yet. Create employee users in Supabase Authentication." />}</div></Panel><Panel eyebrow="Field activity" title="Latest check-ins">{data.visits.length ? <div className="divide-y divide-slate-100">{data.visits.slice(0, 6).map((visit) => <div className="flex gap-3 py-3.5" key={visit.id}><span className="mt-0.5 rounded-xl bg-emerald-100 p-2 text-emerald-700"><FiMapPin /></span><div className="min-w-0 flex-1"><p className="font-bold">{visit.customer_name}</p><p className="truncate text-xs text-slate-500">{visit.employee_profiles?.full_name} · {visit.visit_type} · {visit.village || "No village"}</p>{visit.photo_url && <a className="mt-1 inline-block text-xs font-bold text-emerald-700 hover:underline" href={visit.photo_url} target="_blank" rel="noreferrer">View visit photo</a>}</div><span className="whitespace-nowrap text-xs text-slate-400">{new Date(visit.checked_in_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div> : <Empty text="No check-ins recorded today." />}</Panel></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel eyebrow="GPS records" title="Location & route data">{stats.active.length ? <div className="space-y-3">{stats.active.map((item) => <div className="rounded-2xl bg-emerald-50 p-4" key={item.id}><p className="font-bold">{item.employee_profiles?.full_name}</p><p className="mt-1 text-sm text-slate-600">Start location: {item.start_latitude?.toFixed?.(5) || "—"}, {item.start_longitude?.toFixed?.(5) || "—"}</p><a target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-sm font-bold text-emerald-700 hover:underline" href={`https://www.google.com/maps?q=${item.start_latitude},${item.start_longitude}`}>Open location <FiChevronRight /></a></div>)}</div> : <Empty text="Active employee GPS locations will appear here after they start their day." />}</Panel><Panel eyebrow="Financial activity" title="Orders, collections & expenses">{data.transactions.length ? <div className="divide-y divide-slate-100">{data.transactions.slice(0, 7).map((transaction) => <div className="flex items-center justify-between gap-3 py-3" key={transaction.id}><div><p className="font-bold">{transaction.party_name}</p><p className="text-xs text-slate-500">{transaction.transaction_type} · {transaction.employee_profiles?.full_name}</p></div><p className="font-black text-emerald-700">{money(transaction.amount)}</p></div>)}</div> : <Empty text="No financial entries today." />}</Panel></section>
  </section>;
  if (embedded) return content;
  return <main className="min-h-screen bg-[#f6f8f7] text-slate-800"><header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><img src="/logo.webp" alt="Reliaf" className="h-10 w-10 rounded-xl object-cover" /><div><p className="font-black text-emerald-800">Reliaf Track</p><p className="text-xs text-slate-500">Administrator command center</p></div></div><button onClick={async () => { await supabase.auth.signOut(); navigate("/employee-tracking/admin-login"); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-600 transition hover:border-rose-200 hover:text-rose-600"><FiLogOut /> Logout</button></div></header>{content}</main>;
}
function Metric({ icon, label, value, note, tone }) { const tones = { emerald: "bg-emerald-50 text-emerald-700", lime: "bg-lime-50 text-lime-700", sky: "bg-sky-50 text-sky-700", violet: "bg-violet-50 text-violet-700", amber: "bg-amber-50 text-amber-700" }; return <div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><span className={`inline-flex rounded-xl p-2.5 ${tones[tone]}`}>{icon}</span><p className="mt-3 text-2xl font-black text-slate-900">{value}</p><p className="mt-0.5 text-sm font-bold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>; }
function ProgressRing({ value }) { return <div className="grid h-32 w-32 place-items-center rounded-full" style={{ background: `conic-gradient(#059669 ${value * 3.6}deg, #d1fae5 0deg)` }}><div className="grid h-[104px] w-[104px] place-items-center rounded-full bg-white"><div className="text-center"><p className="text-3xl font-black text-slate-900">{value}%</p><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Checked in</p></div></div></div>; }
function Panel({ eyebrow, title, children }) { return <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-xl font-black text-slate-900">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text }) { return <p className="rounded-2xl bg-slate-50 px-4 py-6 text-sm leading-6 text-slate-500">{text}</p>; }
